import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import "../access/firebase";
import styles from "../styles/Home.module.css";
import "antd/dist/antd.css";
import { Layout } from "antd";
import { Content } from "antd/lib/layout/layout";
import { LinkForm } from "../features/AddLinkForm";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <Content style={{ margin: "5% 0" }}>
          <div className={styles.formContainer}>
            <LinkForm />
          </div>
        </Content>
      </Layout>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
